//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MProjectWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class caracteristicas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public caracteristicas()
        {
            this.actividades = new HashSet<actividades>();
            this.archivos = new HashSet<archivos>();
            this.proyectos = new HashSet<proyectos>();
        }
    
        public string keym { get; set; }
        public long idx_caracteristica { get; set; }
        public long id_caracteristica { get; set; }
        public long id_usuario { get; set; }
        public string estado { get; set; }
        public Nullable<long> porcentaje_asignado { get; set; }
        public Nullable<long> porcentaje_cumplido { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public string tipo_caracteristica { get; set; }
        public Nullable<long> padre_caracteristica { get; set; }
        public Nullable<long> proyecto_padre { get; set; }
        public bool visualizar_superior { get; set; }
        public System.DateTime fecha_ultima_modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actividades> actividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<archivos> archivos { get; set; }
        public virtual asignaciones asignaciones { get; set; }
        public virtual usuarios_meta_datos usuarios_meta_datos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proyectos> proyectos { get; set; }
    }
}
