//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MProjectWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class caracteristica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public caracteristica()
        {
            this.archivos = new HashSet<archivo>();
            this.caracteristicas1 = new HashSet<caracteristica>();
        }
    
        public long id_caracteristica { get; set; }
        public string estado { get; set; }
        public Nullable<long> porcentaje_asignado { get; set; }
        public Nullable<long> porcentaje_cumplimido { get; set; }
        public Nullable<long> duracion { get; set; }
        public string tipo_duracion { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public long id_actividad { get; set; }
        public long id_proyecto { get; set; }
        public Nullable<long> padre_caracteristica { get; set; }
        public Nullable<long> proyecto_padre { get; set; }


    
        public virtual actividade actividade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<archivo> archivos { get; set; }
        public virtual proyecto proyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<caracteristica> caracteristicas1 { get; set; }
        public virtual caracteristica caracteristica1 { get; set; }
        public virtual proyecto proyecto1 { get; set; }
    }
}
