//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MProjectWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantillas_meta_datos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plantillas_meta_datos()
        {
            this.proyectos_meta_datos = new HashSet<proyectos_meta_datos>();
        }
    
        public long id_plantilla_meta_dato { get; set; }
        public long id_plantilla { get; set; }
        public long id_meta_datos { get; set; }
        public bool requerido { get; set; }
    
        public virtual meta_datos meta_datos { get; set; }
        public virtual plantilla plantilla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proyectos_meta_datos> proyectos_meta_datos { get; set; }
    }
}
