//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MProjectWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantillas_meta_datos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plantillas_meta_datos()
        {
            this.proyectos_meta_datos = new HashSet<proyectos_meta_datos>();
        }
    
        public long id_plantilla_meta_dato { get; set; }
        public long id_plantilla { get; set; }
        public long id_meta_datos { get; set; }
        public bool requerido { get; set; }
    
        public virtual meta_datos meta_datos { get; set; }
        public virtual plantillas plantillas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proyectos_meta_datos> proyectos_meta_datos { get; set; }
    }
}
