//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MProjectWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyectos_meta_datos
    {
        public long id_proyecto_meta_dato { get; set; }
        public string valor { get; set; }
        public long id_proyecto { get; set; }
        public long id_plantilla_meta_dato { get; set; }
    
        public virtual plantillas_meta_datos plantillas_meta_datos { get; set; }
        public virtual proyecto proyecto { get; set; }
    }
}
