//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MProjectWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyectos_meta_datos
    {
        public long id_proyecto_meta_dato { get; set; }
        public string valor { get; set; }
        public long id_proyecto { get; set; }
        public long id_plantilla_meta_dato { get; set; }
    
        public virtual plantillas_meta_datos plantillas_meta_datos { get; set; }
        public virtual proyectos proyectos { get; set; }
    }
}
