//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MProjectWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyectos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proyectos()
        {
            this.proyectos_meta_datos = new HashSet<proyectos_meta_datos>();
        }
    
        public string keym { get; set; }
        public long idx_proyecto { get; set; }
        public long idx_caracteristica { get; set; }
        public long id_proyecto { get; set; }
        public long id_caracteristica { get; set; }
        public long id_usuario { get; set; }
        public string nombre { get; set; }
        public string plantilla { get; set; }
        public bool IR_proyecto { get; set; }
        public string icon { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_ultima_modificacion { get; set; }
        public Nullable<long> contador { get; set; }
    
        public virtual caracteristicas caracteristicas { get; set; }
        public virtual usuarios_meta_datos usuarios_meta_datos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proyectos_meta_datos> proyectos_meta_datos { get; set; }
    }
}
