//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MProjectWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public long id_usuario { get; set; }
        public string pass { get; set; }
        public bool administrador { get; set; }
    
        public virtual usuarios_meta_datos usuarios_meta_datos { get; set; }
    }
}
