//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantillas_meta_datos
    {
        public string keym { get; set; }
        public long idx_plantilla_meta_dato { get; set; }
        public long idx_plantilla { get; set; }
        public long idx_meta_dato { get; set; }
        public long id_plantilla_meta_dato { get; set; }
        public long id_plantilla { get; set; }
        public long id_meta_dato { get; set; }
        public long id_usuario { get; set; }
        public bool requerido { get; set; }
        public System.DateTime fecha_ultima_modificacion { get; set; }
    
        public virtual meta_datos meta_datos { get; set; }
        public virtual plantillas plantillas { get; set; }
        public virtual usuarios_meta_datos usuarios_meta_datos { get; set; }
    }
}
