//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyectos_meta_datos
    {
        public string keym { get; set; }
        public long idx_proyecto_meta_dato { get; set; }
        public long idx_proyecto { get; set; }
        public long id_proyecto_meta_dato { get; set; }
        public long id_proyecto { get; set; }
        public string valor { get; set; }
        public bool is_title { get; set; }
        public string tipo { get; set; }
        public long id_usuario { get; set; }
        public System.DateTime fecha_ultima_modificacion { get; set; }
    
        public virtual proyectos proyectos { get; set; }
        public virtual usuarios_meta_datos usuarios_meta_datos { get; set; }
    }
}
