//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_sequence
    {
        public Nullable<long> actividades { get; set; }
        public Nullable<long> archivos { get; set; }
        public Nullable<long> caracteristicas { get; set; }
        public Nullable<long> costos { get; set; }
        public Nullable<long> proyectos { get; set; }
        public Nullable<long> proyectos_meta_datos { get; set; }
        public Nullable<long> recursos { get; set; }
        public Nullable<long> presupuesto { get; set; }
        public long id_usuario { get; set; }
    
        public virtual usuarios_meta_datos usuarios_meta_datos { get; set; }
    }
}
